# Generated by Django 3.2.16 on 2022-12-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs_generated',
            name='username',
        ),
    ]
